### ISSUE TITLE
I'd like to be able to check response headers

### ISSUE THREAD

**Issue by niels-vd** [testxio/testx-http-keywords#2]
Adding headers to the get or post is a very nice feature, but I'd like to be able to check the response headers as well

**Comment by greyarch** [comment]
How exactly do you want to check the response headers? I propose a parameter 'expected headers' that has the same format as the 'headers' parameter. Each header you specify there will be expected to exist and has the specified value. This way you will not have to specify all response headers, but only the ones you are interested in. However, this way you will not be able to check if the response contains headers you do not expect. I don't think this will be a problem, but maybe I am not seeing something.

**Comment by niels-vd** [comment]
Your proposed solution sounds just fine. I'm interested in verifying the presence (and content) of specific (custom) headers. I'm not interested in the presence (and content) of all headers.

**Comment by greyarch** [comment]
Implemented in [0.7.0](https://github.com/testxio/testx-http-keywords/releases/tag/0.7.0)

**Comment by niels-vd** [comment]
thanks!
