### ISSUE TITLE
"body" argument doesn't support XML

### ISSUE THREAD

**Issue by niels-vd** [testxio/testx-http-keywords#5]
I tried to use the body argument to send an XML post request. The result is a post body with an escape character before each ". -> \"

The application can't handle the resulting message body. Is there a way to make this work?

**Comment by greyarch** [comment]
@niels-vd can you attach the relevant part of your testx file here?

**Comment by niels-vd** [comment]
@greyarch it seems like you were right and the error was in the Content-Type header. I think I used the wrong XML header. So I'll close this one
