### ISSUE TITLE
expected response (regex) uses type 'object' instead of 'json'

### ISSUE THREAD

**Issue by niels-vd** [testxio/testx-http-keywords#7]
When using expected response a json body is seen as type 'object'

example:
- send http post request [zendt setSchutting met ongeldige schuttingRichting]:
    url: "http://ivs-sbpn-app.ivs-sbpn-niels.rws.ictu:8080/ivs-sbpn-backend/rest/v2/schutting"
    headers: '"Authorization='Basic YWRtaW46YWRtaW4=';BusinessEventId='fe00d9b0-729d-11e7-8090-471f8785e1ce';TraceerNummer='fe00d9b0-729d-11e7-8090-471f8785e1ce';BerichtNummer='fe00d9b0-729d-11e7-8090-471f8785e1ce';GebruikersID='niels';SysteemID='ivs-sbpn-backend';SysteemVersie='1.23.0-headers-SNAPSHOT';TimeStamp='Wed, 21 Jun 2017 07:43:58 GMT';CorellatieNummer='fe00d9b0-729d-11e7-8090-471f8785e1ce'"'
    json: '{
            "deelkolknummer": "0",
            "isrsCodeKolk": "NLPLP001430957100223",
            "schuttingDatum": "2017-10-17",
            "schuttingRichting": "VAART",
            "schuttingStatus": "GEPLAND",
            "tijdstipGeplandInvarenGroen": "2017-10-17T12:50:25.456Z"
          }'
    expected status code: '400'
    expected response: test

**Comment by greyarch** [comment]
Fixed in [0.14.3](https://github.com/testxio/testx-http-keywords/releases/tag/0.14.3)
